GET https://localhost:5002/api/v1/movie/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlZsVzVJTm96Z2g4RXB1Z2pXM1lOQyJ9.eyJpc3MiOiJodHRwczovL3NmZi1vb3AyLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJ3QjVJODJ4VW94VTV0RlNYNXNvOW0zS1JHbTEzcEVLSUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMi8iLCJpYXQiOjE2MTg5NTAwMzMsImV4cCI6MTYxOTAzNjQzMywiYXpwIjoid0I1STgyeFVveFU1dEZTWDVzbzltM0tSR20xM3BFS0kiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.sPzHM_XG8uM7cdk9NHktzY7zRo75m6UT6prsQfV1lrEFWA3AyQ_2w9Cmxt6mkJHtuWd6pZLGNyRmW0puK5mT8P40d9PjrWSZgii9SokqlqD0CQknZbXKyiGkAJ1DogSbr1_WeHWpyl8PUi5YN73Cz2UtG7dCxYForePKa1aN7cNohh38SxD46bR3HPLBuA3Gm5YzTwxVBR0ZfZ6TLmb9hpLoRt0Nn-oDEdAVaK3fwNUJmem1isu-Wu5qr7eENjrKvwQjugPiJhjLely-R6MsTjhKdysRIQFDxrxmH411y8UZ2_Te1Y_qWdH_1XFn6FaIiRpl5pE0ly9Wo-M0OllM9w

